---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mazikai.
--- DateTime: 2022/7/11 11:37
---
local key = KEYS[1]
local time = tonumber(ARGV[1])
local count = tonumber(ARGV[2])
local current = redis.call('get', key)
if current and tonumber(current) > count then
    return tonumber(current)
end
current = redis.call('incr', key)
if tonumber(current) == 1 then
    redis.call('expire', key, time)
end
return tonumber(current)